In [2]:
import numpy as np
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [3]:
arr_2d[0][2]

30

In [4]:
arr_2d[2,0]

70

In [7]:
import numpy as np
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
arr_2d[1][2]

60

In [10]:
arr_2d[2,2]

90

In [13]:
arr_2d[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [20]:
arr_2d[:2,:1]

array([[10],
       [40]])

In [31]:
arr_2d[0:,2:]

array([[30],
       [60],
       [90]])

In [22]:
arr_2d[:1]

array([[10, 20, 30]])

In [23]:
arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
arr_2d[2:,1:]

array([[80, 90]])

In [64]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
bool_arr=arr>5

In [67]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr<5]

array([1, 2, 3, 4])

In [81]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
arr_2d[3:,1:5]

array([[31, 32, 33, 34],
       [41, 42, 43, 44]])

In [76]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [83]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
2*(arr)-arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
import numpy as np


In [7]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
2*(arr)/2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
arr/arr

<ipython-input-10-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1/arr

<ipython-input-11-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [12]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
arr**(1/2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [20]:
np.max(arr)

10

In [21]:
np.min(arr)

0

In [22]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [23]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [24]:
np.log(arr)

<ipython-input-24-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [26]:
np.sinh(arr)

array([0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
       2.72899172e+01, 7.42032106e+01, 2.01713157e+02, 5.48316123e+02,
       1.49047883e+03, 4.05154190e+03, 1.10132329e+04])

In [30]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[0:11]=0.
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr=np.arange(1,11)
arr

In [38]:
arr[0:11]=1
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
arr[0:11]=5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [42]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [45]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
arr=np.random.rand(1)
arr

array([0.70886695])

In [53]:
arr=np.random.randn(25)
arr

array([-0.48506709, -0.36049563, -0.96306045,  0.40655134,  0.08756829,
       -0.48184568,  0.4508461 ,  0.41611268,  0.65244279, -1.71436226,
       -0.73306771,  0.4114013 ,  1.23281697,  0.18189609, -0.86809455,
        0.10410416, -0.87428703,  0.91798838,  0.39028532, -0.79404977,
        1.18285404,  1.2726721 , -0.55747877,  1.3659615 ,  0.4905362 ])

In [59]:
arr=np.arange(10,10)
arr

array([], dtype=int32)

In [110]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [76]:
x = np.arange(8.0,40,10)
#np.split(x, [3, 5, 6, 10])
x

array([ 8., 18., 28., 38.])

In [79]:
np.random.rand(0,100)

array([], shape=(0, 100), dtype=float64)

In [ ]:
np.arange(1,25).reshape(5,5)

In [84]:
x=np.arange(1,26).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
x[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [86]:
x[3,4]

20

In [95]:
x[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [96]:
x[4:]

array([[21, 22, 23, 24, 25]])

In [98]:
x[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
np.sum(x)

325

In [111]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [114]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [118]:
np.std(mat)

7.211102550927978

In [122]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])