In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [6]:
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [8]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)
np.arange(0,10,3)

array([0, 3, 6, 9])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((4))

array([1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.linspace(0,3,20)

array([0.        , 0.15789474, 0.31578947, 0.47368421, 0.63157895,
       0.78947368, 0.94736842, 1.10526316, 1.26315789, 1.42105263,
       1.57894737, 1.73684211, 1.89473684, 2.05263158, 2.21052632,
       2.36842105, 2.52631579, 2.68421053, 2.84210526, 3.        ])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.rand(5)

array([0.11770677, 0.29239864, 0.84819207, 0.87035731, 0.95150503])

In [2]:
import numpy as np
np.random.rand(5,5)

array([[0.98708314, 0.8713987 , 0.6275342 , 0.86611172, 0.79353338],
       [0.31534604, 0.75329532, 0.52230574, 0.13011889, 0.54515718],
       [0.10694346, 0.57756393, 0.83448786, 0.13570332, 0.69336133],
       [0.71418695, 0.06989518, 0.7426837 , 0.81434106, 0.19404953],
       [0.37699359, 0.95701114, 0.49391765, 0.71058519, 0.06970171]])

In [5]:
import numpy as np
np.random.randint(1,100)

24

In [6]:
np.random.randint(1,100,10)

array([71, 86, 60, 81, 41, 76, 14, 10, 67, 17])

In [8]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
ranarr=np.random.randint(0,50,100)
ranarr

array([12, 36, 48, 26, 15, 22, 41, 42, 31, 34, 41, 22, 45, 28, 21, 48, 38,
       38, 36, 25, 16,  5, 12, 16, 29, 43, 16, 25, 25, 23, 32,  0, 44, 20,
        8, 48, 44, 29, 23, 45, 42, 32, 43, 44, 22,  9, 35, 30, 36, 32,  8,
       42, 36, 48, 23, 42, 39, 28, 26, 32, 33, 10, 17, 26, 37, 44, 41, 35,
       39,  9, 23, 36, 24, 31, 19, 42,  0, 37, 10,  5, 36, 21, 25, 44, 40,
        1, 29, 46, 30, 43,  9, 21,  7, 39, 11,  5,  3, 40, 13, 41])

In [10]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
arr.reshape(10,10)

ValueError: cannot reshape array of size 25 into shape (10,10)

In [12]:
ranarr.max()

48

In [13]:
ranarr.min()

0

In [14]:
ranarr

array([12, 36, 48, 26, 15, 22, 41, 42, 31, 34, 41, 22, 45, 28, 21, 48, 38,
       38, 36, 25, 16,  5, 12, 16, 29, 43, 16, 25, 25, 23, 32,  0, 44, 20,
        8, 48, 44, 29, 23, 45, 42, 32, 43, 44, 22,  9, 35, 30, 36, 32,  8,
       42, 36, 48, 23, 42, 39, 28, 26, 32, 33, 10, 17, 26, 37, 44, 41, 35,
       39,  9, 23, 36, 24, 31, 19, 42,  0, 37, 10,  5, 36, 21, 25, 44, 40,
        1, 29, 46, 30, 43,  9, 21,  7, 39, 11,  5,  3, 40, 13, 41])

In [16]:
ranarr.argmax()

2

In [17]:
arr.shape

(25,)

In [18]:
arr=arr.reshape(5,5)
arr.shape

(5, 5)

In [19]:
arr.shape

(5, 5)

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.dtype

dtype('int32')

In [22]:
from numpy.random import randint

In [23]:
randint(2,10)

7

In [6]:
import numpy as np
arr=np.arange(25)
arr
arr.dtype



dtype('int32')

In [11]:
from numpy.random import randint
randint(2,10,8)

array([2, 7, 9, 6, 3, 8, 7, 7])

In [ ]:
import numpy as np


In [16]:
arr=np.arange(0,11)
arr

In [13]:
arr[9]

9

In [17]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr[0:12:2]

array([ 0,  2,  4,  6,  8, 10])

In [23]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[:10:-1]

array([], dtype=int32)

In [29]:
arr[0:4]=50
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [46]:
slice_of_arr[:] = 99
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy=arr.copy()

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_copy[:]=100

In [52]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])